//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.userinfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtuname;
		protected global::System.Web.UI.WebControls.TextBox txtusex;
		protected global::System.Web.UI.WebControls.TextBox txtuage;
		protected global::System.Web.UI.WebControls.TextBox txtuphone;
		protected global::System.Web.UI.WebControls.TextBox txtuemail;
		protected global::System.Web.UI.WebControls.TextBox txtwid;
		protected global::System.Web.UI.WebControls.TextBox txtwname;
		protected global::System.Web.UI.WebControls.TextBox txtparameter1;
		protected global::System.Web.UI.WebControls.TextBox txtparameter2;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
