//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.userinfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lbluname;
	protected global::System.Web.UI.WebControls.Label lblusex;
	protected global::System.Web.UI.WebControls.Label lbluage;
	protected global::System.Web.UI.WebControls.Label lbluphone;
	protected global::System.Web.UI.WebControls.Label lbluemail;
	protected global::System.Web.UI.WebControls.Label lblwid;
	protected global::System.Web.UI.WebControls.Label lblwname;
	protected global::System.Web.UI.WebControls.Label lblparameter1;
	protected global::System.Web.UI.WebControls.Label lblparameter2;


       
    }
}
